when:
  instance: ci.schnabel.org
  repo: kokuwaio/shellcheck
  event: push
  branch: main
  path: [.woodpecker/build.yaml, .woodpecker/push.yaml, Dockerfile, Dockerfile.dockerignore, entrypoint.sh]

depends_on: [build]
skip_clone: true

steps:

  manifest:
    image: mplatform/manifest-tool:alpine-v2.1.9
    commands: manifest-tool push from-args
        --platforms=linux/amd64,linux/arm64
        --template=ci-registry.schnabel.org/kokuwaio/shellcheck:$CI_PIPELINE_NUMBER-ARCH
        --target=ci-registry.schnabel.org/kokuwaio/shellcheck:$CI_PIPELINE_NUMBER

  docker.io: &push
    image: quay.io/skopeo/stable:v1.17.0
    depends_on: [manifest]
    commands:
      - skopeo inspectdocker://ci-registry.schnabel.org/kokuwaio/shellcheck:$CI_PIPELINE_NUMBER
      - skopeo copy $SOURCE_IMAGE $DEST_IMAGE:v0.9.0 --dest-username=$DEST_USERNAME --dest-password=$DEST_PASSWORD --preserve-digests --all
      - skopeo copy $SOURCE_IMAGE $DEST_IMAGE:latest --dest-username=$DEST_USERNAME --dest-password=$DEST_PASSWORD --preserve-digests --all
    environment:
      SOURCE_IMAGE: 
      DEST_IMAGE: docker://$DEST_URL/kokuwaio/shellcheck
      DEST_URL: docker.io
      DEST_USERNAME: {from_secret: DOCKER_IO_USERNAME}
      DEST_PASSWORD: {from_secret: DOCKER_IO_PASSWORD}

  ghcr.io:
    <<: *push
    environment:
      DEST_URL: ghcr.io
      DEST_USERNAME: {from_secret: GHCR_IO_USERNAME}
      DEST_PASSWORD: {from_secret: GHCR_IO_PASSWORD}
