when:
  event: [cron, manual, push]
  branch: main
  path: [.woodpecker/*.yaml, Dockerfile, Dockerfile.dockerignore, entrypoint.sh]
  instance: ci.schnabel.org
  repo: kokuwaio/shellcheck

depends_on: [push]
matrix:
  PLATFORM: [amd64, arm64]
labels:
  platform: linux/${PLATFORM}

steps:

  test:
    image: kokuwaio/shellcheck
    pull: true
